# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Administrator\Desktop\Temporary Files\Cypress_Lowpower\Lowpower\LowpowerMode\Deepsleep.cydsn\Deepsleep.cyprj
# Date: Sun, 26 Nov 2017 07:40:54 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Administrator\Desktop\Temporary Files\Cypress_Lowpower\Lowpower\LowpowerMode\Deepsleep.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Administrator\Desktop\Temporary Files\Cypress_Lowpower\Lowpower\LowpowerMode\Deepsleep.cydsn\Deepsleep.cyprj
# Date: Sun, 26 Nov 2017 07:40:51 GMT
