# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Administrator\Desktop\Temporary Files\Cypress_Lowpower\Lowpower\LowpowerMode\Hibernate.cydsn\Hibernate.cyprj
# Date: Sun, 26 Nov 2017 07:06:20 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 166.66666666666666 -waveform {0 83.3333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFClk} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyIMO} -period 166.66666666666666 -waveform {0 83.3333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 166.66666666666666 -waveform {0 83.3333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 333.33333333333331 -waveform {0 83.3333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Administrator\Desktop\Temporary Files\Cypress_Lowpower\Lowpower\LowpowerMode\Hibernate.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Administrator\Desktop\Temporary Files\Cypress_Lowpower\Lowpower\LowpowerMode\Hibernate.cydsn\Hibernate.cyprj
# Date: Sun, 26 Nov 2017 07:06:17 GMT
